import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "React Dose App",
  description: "Generated by React Dose CLI",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
